### PR TITLE
SOFTWARE-2988 (Add README for usage of scripts)

### PR DESCRIPTION
**Pull request by efajardo**
As part of [SOFTWARE-2988](https://jira.opensciencegrid.org/browse/SOFTWARE-2988) moving the usage to separate README in this repo.

### CODE REVIEW

**Comment by efajardo** [comment]
@brianhlin Well I could but I thought it would be easier to maintain if we have separate usage README for each script. Do you want me to separate them?. I am sorry but the wording of the  ticket was not clear.

**Comment by brianhlin** [comment]
The problem with keeping them in separate READMEs is that it's not as user friendly. Please combine them all into `README.md`

**Comment by brianhlin** [comment]
@efajardo when will you be able to get to this again?

**Comment by efajardo** [comment]
@brianhlin  I added all one can you please merge this?

**Pull request merged**
