### PR TITLE
Setup pre-commit with useful plugins

### PR DESCRIPTION
**Pull request by jcpunk**
This adds support for [pre-commit](https://pre-commit.com/#usage) to the repo which can greatly simplify consistent code practices.

### CODE REVIEW

**Review by DrDaveD — CHANGES_REQUESTED** [review]
The new pre-commit check fails.

What was the inspiration for this?

**Comment by brianhlin** [comment]
I've always wanted to play around with pre-commit and black but have always been hesitant because I haven't gone through the trouble of making sure black doesn't royally screw up git blame. If we address that and make sure that we still support Python 3.6, I could be open to this.

**Comment by brianhlin** [comment]
Oh and I missed that you're using the `pre-commit` [action](https://github.com/pre-commit/action),

> this action is in maintenance-only mode and will not be accepting new features.
>
> generally you want to use [pre-commit.ci](https://pre-commit.ci/) which is faster and has more features.

**Comment by bbockelm** [comment]
@brianhlin - you want https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view .

And yes, precommit tries to bump you to their CI.  I tend to just ignore that.

**Comment by jcpunk** [comment]
> The new pre-commit check fails.
> 
> What was the inspiration for this?

If you're interested in going with these tools, some automation to keep folks in sync is usually helpful.

**Comment by DrDaveD** [comment]
We can't use it if it fails the check.  Do you plan to fix it?

The tools in this package are quite small and hardly seem worth spending much effort on.

**Comment by jcpunk** [comment]
``` toml
float_to_top = "True"
```

Might need to be removed because of `osg-cert-request` and `osg-incommon-request` depending on how you're calling them.

I'd be tempted to use `entrypoint: [console_scripts`](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) to generate them more dynamically.

**Comment by DrDaveD** [comment]
> float_to_top = "True"
>
> Might need to be removed because of osg-cert-request and osg-incommon-request depending on how you're calling them.

What do you mean?  What type of way of calling them would be tripped up by `float_to_top = "True"`.

> I'd be tempted to use entrypoint: [console_scripts](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) to generate them more dynamically.

How does that help?

**Comment by jcpunk** [comment]
> What do you mean? What type of way of calling them would be tripped up by `float_to_top = "True".`

It looks like the scripts are expecting to adjust `sys.path` before finishing the imports.  With `float_to_top = True` the `isort` tool will move all the imports to the top of the scope.  This may not be what you're expecting for these scripts.

The setuptools console_scripts will generate these `"/usr/bin/"` scripts dynamically so you don't need to write/maintain/separate these out.  Use of these setuptools hooks should in theory reduce your long term burden.  We've had good success with those in the HepCloud DecisionEngine.

**Comment by jcpunk** [comment]
Added the ignore revs file

**Comment by brianhlin** [comment]
@jcpunk it looks like those Python path hacks are just that, hacks to make unit testing happy and to make life easier when running in a virtualenv. I would definitely like both to continue working so if you've got alternate suggestions for those use cases, I'm all ears!

**Comment by jcpunk** [comment]
I think my current PR should leave them in place.

**Comment by brianhlin** [comment]
In that case, I'm happy with this unless @DrDaveD has any other thoughts

**Pull request merged**
