### PR TITLE
add BuildRequires: m2crypto

### PR DESCRIPTION
**Pull request by DrDaveD**
This is needed to build on osg-build koji.

I also put it for now in the subversion build repository so I don't need a new tag for this.

### CODE REVIEW

**Comment by brianhlin** [comment]
Why isn't `Requires: m2crypto` not sufficient?

**Comment by DrDaveD** [comment]
Without that, it dies during the build.  Here's a [scratch build without it](http://koji.chtc.wisc.edu/kojifiles/work/tasks/8146/288146/build.log).  It's dying in setup.py.  Oh, that's because setup.py is importing utils.  Why would it do that?

**Comment by DrDaveD** [comment]
Oh, it's to get the version number.

**Comment by brianhlin** [comment]
In that case, I think the right thing to do is to move the `Csr` class and `get_ssl_context` to `request.py` and get rid of the BuildRequires

**Comment by jteheran** [comment]
Yes, I just created it: https://github.com/opensciencegrid/osg-pki-tools/issues/46

**Comment by brianhlin** [comment]
Thanks @jteheran. Closing this in favor of the solution to #46

**Pull request closed without merging**
